[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = ["pip install --break-system-packages --no-cache-dir -r requirements.txt"]

[phases.build]
cmds = ["python -c 'print(\"Build completed successfully\")'"]

[start]
cmd = "python app.py"

[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"